version: "3"
services:
  bot:
    restart: always
    build: .
    depends_on:
      - postgres
    environment:
      - TOKEN=1162626752:AAHoQt0cavSWIeKKke7UvQT39DLifN71xNU

  postgres:
    restart: always
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=pass